-- DropForeignKey
ALTER TABLE "OpWorkEmployer" DROP CONSTRAINT "FK_OPWORK_EMPLOYER__PROFILE_ID";

-- DropForeignKey
ALTER TABLE "OpWorkJobSeeker" DROP CONSTRAINT "FK_OPWORK_JOB_SEEKER__PROFILE_ID";

-- DropForeignKey
ALTER TABLE "OpWorkProject" DROP CONSTRAINT "FK_OPWORK_PROJECT__PROFILE_ID";

-- DropIndex
DROP INDEX "UQ_OPWORK_EMPLOYER__PROFILE_ID";

-- DropIndex
DROP INDEX "UQ_OPWORK_JOB_SEEKER__PROFILE_ID";

-- DropIndex
DROP INDEX "UQ_OPWORK_PROJECT__PROFILE_ID";

-- AlterTable
ALTER TABLE "OpWorkEmployer" ADD COLUMN     "opWorkProfileId" UUID;

-- AlterTable
ALTER TABLE "OpWorkJobSeeker" ADD COLUMN     "opWorkProfileId" UUID;

-- AlterTable
ALTER TABLE "OpWorkProject" ADD COLUMN     "opWorkProfileId" UUID;

-- AddForeignKey
ALTER TABLE "OpWorkJobSeeker" ADD CONSTRAINT "FK_OPWORK_JOB_SEEKER__PROFILE_ID" FOREIGN KEY ("opWorkProfileId") REFERENCES "OpWorkProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OpWorkEmployer" ADD CONSTRAINT "FK_OPWORK_EMPLOYER__PROFILE_ID" FOREIGN KEY ("opWorkProfileId") REFERENCES "OpWorkProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OpWorkProject" ADD CONSTRAINT "FK_OPWORK_PROJECT__PROFILE_ID" FOREIGN KEY ("opWorkProfileId") REFERENCES "OpWorkProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;
