import { OpWorkSkillType } from '../generated/prisma/enums';

export const SKILL_CATEGORIES = {
  [OpWorkSkillType.CORE_DEVELOPMENT__PROGRAMMING_LANGUAGE]: [
    'JavaScript',
    'TypeScript',
    'Python',
    'Java',
    'Go',
    'Rust',
    'Kotlin',
    'Swift',
    'C#',
    'C++',
    'PHP',
    'Ruby',
    'Scala',
    'Elixir',
    'Haskell',
    'Dart',
    'Lua',
    'Perl',
    'Objective-C',
  ],
  [OpWorkSkillType.CORE_DEVELOPMENT__FRAMEWORK]: [
    'React',
    'Next.js',
    'Vue',
    'Nuxt.js',
    'Angular',
    'Svelte',
    'NestJS',
    'Express',
    'Fastify',
    'Django',
    'Flask',
    'Spring Boot',
    'Ruby on Rails',
    'ASP.NET Core',
    'Flutter',
    'React Native',
  ],
  [OpWorkSkillType.CORE_DEVELOPMENT__LIBRARY]: [
    'Redux',
    'RxJS',
    'Lodash',
    'TensorFlow',
    'Pandas',
    'NumPy',
    'Matplotlib',
    'Seaborn',
    'D3.js',
    'Chart.js',
    'Three.js',
    'Jest',
    'Mocha',
    'Chai',
  ],
  [OpWorkSkillType.CORE_DEVELOPMENT__RUNTIME]: [
    'Node.js',
    'Deno',
    'JVM',
    '.NET CLR',
    'Python Interpreter',
    'Go Runtime',
  ],
  [OpWorkSkillType.CORE_DEVELOPMENT__API_TECHNOLOGY]: [
    'REST',
    'GraphQL',
    'gRPC',
    'WebSocket',
    'JSON-RPC',
  ],
  [OpWorkSkillType.CORE_DEVELOPMENT__ARCHITECTURE_PATTERN]: [
    'Microservices',
    'Monolith',
    'Event-Driven Architecture',
    'Serverless Architecture',
  ],
  [OpWorkSkillType.CORE_DEVELOPMENT__ARCHITECTURE_METHOD]: [
    'Clean Architecture',
    'Domain-Driven Design',
    'Hexagonal Architecture',
    'CQRS',
  ],

  [OpWorkSkillType.DATA_AI__DATABASE]: [
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Redis',
    'MariaDB',
    'SQLite',
    'Cassandra',
    'DynamoDB',
    'Neo4j',
    'Elasticsearch',
  ],
  [OpWorkSkillType.DATA_AI__DATA_WAREHOUSE]: [
    'BigQuery',
    'Snowflake',
    'Redshift',
    'Azure Synapse',
  ],
  [OpWorkSkillType.DATA_AI__BIG_DATA]: [
    'Hadoop',
    'Spark',
    'Kafka',
    'Flink',
    'Beam',
  ],
  [OpWorkSkillType.DATA_AI__DATA_ENGINEERING]: [
    'Airflow',
    'dbt',
    'Prefect',
    'Luigi',
  ],
  [OpWorkSkillType.DATA_AI__MACHINE_LEARNING]: [
    'Scikit-learn',
    'XGBoost',
    'LightGBM',
    'CatBoost',
  ],
  [OpWorkSkillType.DATA_AI__DEEP_LEARNING]: [
    'TensorFlow',
    'PyTorch',
    'Keras',
    'MXNet',
  ],
  [OpWorkSkillType.DATA_AI__GENERATIVE_AI]: [
    'OpenAI API',
    'LangChain',
    'RAG',
    'HuggingFace Transformers',
  ],
  [OpWorkSkillType.DATA_AI__COMPUTER_VISION]: ['OpenCV', 'YOLO', 'Detectron2'],
  [OpWorkSkillType.DATA_AI__NLP]: [
    'spaCy',
    'HuggingFace Transformers',
    'NLTK',
    'Gensim',
  ],
  [OpWorkSkillType.DATA_AI__MLOPS]: [
    'MLflow',
    'Kubeflow',
    'Weights & Biases',
    'ClearML',
  ],

  [OpWorkSkillType.DEVOPS_CLOUD__TOOL]: [
    'Git',
    'Docker',
    'Jenkins',
    'Terraform',
    'Ansible',
    'Chef',
    'Puppet',
  ],
  [OpWorkSkillType.DEVOPS_CLOUD__CONTAINERIZATION]: ['Docker', 'Podman', 'LXC'],
  [OpWorkSkillType.DEVOPS_CLOUD__ORCHESTRATION]: [
    'Kubernetes',
    'Nomad',
    'Swarm',
  ],
  [OpWorkSkillType.DEVOPS_CLOUD__CI_CD]: [
    'GitHub Actions',
    'GitLab CI',
    'Jenkins',
    'CircleCI',
  ],
  [OpWorkSkillType.DEVOPS_CLOUD__INFRASTRUCTURE_AS_CODE]: [
    'Terraform',
    'Pulumi',
    'CloudFormation',
  ],
  [OpWorkSkillType.DEVOPS_CLOUD__CONFIGURATION_MANAGEMENT]: [
    'Ansible',
    'Chef',
    'Puppet',
    'SaltStack',
  ],
  [OpWorkSkillType.DEVOPS_CLOUD__PLATFORM]: [
    'AWS',
    'Azure',
    'Google Cloud',
    'Vercel',
    'Heroku',
  ],
  [OpWorkSkillType.DEVOPS_CLOUD__SERVERLESS]: [
    'AWS Lambda',
    'Cloud Functions',
    'Azure Functions',
  ],
  [OpWorkSkillType.DEVOPS_CLOUD__OBSERVABILITY]: [
    'Prometheus',
    'Grafana',
    'OpenTelemetry',
  ],
  [OpWorkSkillType.DEVOPS_CLOUD__MONITORING]: ['Datadog', 'NewRelic', 'Zabbix'],
  [OpWorkSkillType.DEVOPS_CLOUD__NETWORKING]: [
    'TCP/IP',
    'Nginx',
    'Cloudflare',
    'HAProxy',
  ],

  [OpWorkSkillType.SECURITY__CYBERSECURITY]: [
    'OWASP Top 10',
    'Penetration Testing',
    'Vulnerability Assessment',
  ],
  [OpWorkSkillType.SECURITY__APPLICATION_SECURITY]: ['SAST', 'DAST', 'IAST'],
  [OpWorkSkillType.SECURITY__CLOUD_SECURITY]: [
    'IAM',
    'Zero Trust',
    'Cloud Security Posture Management',
  ],
  [OpWorkSkillType.SECURITY__CRYPTOGRAPHY]: [
    'SSL/TLS',
    'JWT',
    'OAuth 2.0',
    'PGP',
  ],

  [OpWorkSkillType.WEB_MOBILE__FRONTEND_TECH]: [
    'HTML5',
    'CSS3',
    'Sass',
    'Webpack',
    'Vite',
  ],
  [OpWorkSkillType.WEB_MOBILE__BACKEND_TECH]: [
    'Express',
    'FastAPI',
    'Spring Boot',
    'NestJS',
  ],
  [OpWorkSkillType.WEB_MOBILE__MOBILE_DEVELOPMENT]: [
    'Flutter',
    'React Native',
    'Swift',
    'Kotlin',
  ],
  [OpWorkSkillType.WEB_MOBILE__GAME_DEVELOPMENT]: [
    'Unity',
    'Unreal Engine',
    'Godot',
  ],
  [OpWorkSkillType.WEB_MOBILE__WEB3]: [
    'Solidity',
    'Ethereum',
    'Web3.js',
    'Hardhat',
    'Truffle',
  ],

  [OpWorkSkillType.QA_PROCESS__TESTING]: [
    'Jest',
    'Cypress',
    'Playwright',
    'Mocha',
    'JUnit',
  ],
  [OpWorkSkillType.QA_PROCESS__PERFORMANCE_TESTING]: ['k6', 'JMeter', 'Locust'],
  [OpWorkSkillType.QA_PROCESS__TEST_AUTOMATION]: [
    'Selenium',
    'TestCafe',
    'Appium',
  ],
  [OpWorkSkillType.QA_PROCESS__DEVELOPMENT_METHODOLOGY]: [
    'Agile',
    'Scrum',
    'Kanban',
    'XP',
  ],
  [OpWorkSkillType.QA_PROCESS__PROJECT_MANAGEMENT]: [
    'Jira',
    'Confluence',
    'Trello',
    'Asana',
  ],
  [OpWorkSkillType.QA_PROCESS__PRODUCT_MANAGEMENT]: [
    'Roadmap Planning',
    'Discovery Workshops',
    'OKRs',
  ],

  [OpWorkSkillType.DESIGN__UI_DESIGN]: ['Figma', 'Sketch', 'Adobe XD'],
  [OpWorkSkillType.DESIGN__UX_RESEARCH]: [
    'User Interviews',
    'A/B Testing',
    'Usability Testing',
  ],
  [OpWorkSkillType.DESIGN__GRAPHIC_DESIGN]: [
    'Photoshop',
    'Illustrator',
    'Affinity Designer',
  ],
  [OpWorkSkillType.DESIGN__MOTION_DESIGN]: [
    'After Effects',
    'Lottie',
    'Blender',
  ],

  [OpWorkSkillType.BUSINESS_MANAGEMENT__LEADERSHIP]: [
    'Leadership',
    'Strategic Thinking',
    'Decision Making',
  ],
  [OpWorkSkillType.BUSINESS_MANAGEMENT__PEOPLE_MANAGEMENT]: [
    'Team Building',
    'Conflict Resolution',
    'Performance Reviews',
  ],
  [OpWorkSkillType.BUSINESS_MANAGEMENT__RECRUITMENT]: [
    'Interviewing',
    'Sourcing Candidates',
    'Talent Acquisition',
  ],
  [OpWorkSkillType.BUSINESS_MANAGEMENT__TECHNICAL_WRITING]: [
    'Documentation',
    'API Docs',
    'Tutorials',
  ],
  [OpWorkSkillType.BUSINESS_MANAGEMENT__SOFT_SKILL]: [
    'Communication',
    'Time Management',
    'Critical Thinking',
    'Teamwork',
  ],

  [OpWorkSkillType.LANGUAGES__LANGUAGE]: [
    'English',
    'German',
    'French',
    'Spanish',
    'Chinese',
    'Japanese',
    'Korean',
    'Russian',
    'Portuguese',
    'Arabic',
  ],

  [OpWorkSkillType.OTHER__EMBEDDED]: [
    'Microcontroller Programming',
    'RTOS',
    'Bare Metal C',
  ],
  [OpWorkSkillType.OTHER__IOT]: ['IoT Devices', 'MQTT', 'Home Automation'],
  [OpWorkSkillType.OTHER__AR_VR]: ['ARKit', 'ARCore', 'Oculus SDK', 'Unity XR'],
  [OpWorkSkillType.OTHER__ROBOTICS]: [
    'ROS',
    'Robot Kinematics',
    'Robotic Process Automation',
  ],
};
