/*
  Warnings:

  - The values [PROGRAMMING_LANGUAGE,FRAMEWORK,DATABASE,TOOL,PLATFORM,LANGUAGE,SOFT_SKILL] on the enum `OpWorkSkillType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "OpWorkSkillType_new" AS ENUM ('CORE_DEVELOPMENT__PROGRAMMING_LANGUAGE', 'CORE_DEVELOPMENT__FRAMEWORK', 'CORE_DEVELOPMENT__LIBRARY', 'CORE_DEVELOPMENT__RUNTIME', 'CORE_DEVELOPMENT__API_TECHNOLOGY', 'CORE_DEVELOPMENT__ARCHITECTURE_PATTERN', 'CORE_DEVELOPMENT__ARCHITECTURE_METHOD', 'DATA_AI__DATABASE', 'DATA_AI__DATA_WAREHOUSE', 'DATA_AI__BIG_DATA', 'DATA_AI__DATA_ENGINEERING', 'DATA_AI__MACHINE_LEARNING', 'DATA_AI__DEEP_LEARNING', 'DATA_AI__GENERATIVE_AI', 'DATA_AI__COMPUTER_VISION', 'DATA_AI__NLP', 'DATA_AI__MLOPS', 'DEVOPS_CLOUD__TOOL', 'DEVOPS_CLOUD__CONTAINERIZATION', 'DEVOPS_CLOUD__ORCHESTRATION', 'DEVOPS_CLOUD__CI_CD', 'DEVOPS_CLOUD__INFRASTRUCTURE_AS_CODE', 'DEVOPS_CLOUD__CONFIGURATION_MANAGEMENT', 'DEVOPS_CLOUD__PLATFORM', 'DEVOPS_CLOUD__SERVERLESS', 'DEVOPS_CLOUD__OBSERVABILITY', 'DEVOPS_CLOUD__MONITORING', 'DEVOPS_CLOUD__NETWORKING', 'SECURITY__CYBERSECURITY', 'SECURITY__APPLICATION_SECURITY', 'SECURITY__CLOUD_SECURITY', 'SECURITY__CRYPTOGRAPHY', 'WEB_MOBILE__FRONTEND_TECH', 'WEB_MOBILE__BACKEND_TECH', 'WEB_MOBILE__MOBILE_DEVELOPMENT', 'WEB_MOBILE__GAME_DEVELOPMENT', 'WEB_MOBILE__WEB3', 'QA_PROCESS__TESTING', 'QA_PROCESS__PERFORMANCE_TESTING', 'QA_PROCESS__TEST_AUTOMATION', 'QA_PROCESS__DEVELOPMENT_METHODOLOGY', 'QA_PROCESS__PROJECT_MANAGEMENT', 'QA_PROCESS__PRODUCT_MANAGEMENT', 'DESIGN__UI_DESIGN', 'DESIGN__UX_RESEARCH', 'DESIGN__GRAPHIC_DESIGN', 'DESIGN__MOTION_DESIGN', 'BUSINESS_MANAGEMENT__LEADERSHIP', 'BUSINESS_MANAGEMENT__PEOPLE_MANAGEMENT', 'BUSINESS_MANAGEMENT__RECRUITMENT', 'BUSINESS_MANAGEMENT__TECHNICAL_WRITING', 'BUSINESS_MANAGEMENT__SOFT_SKILL', 'LANGUAGES__LANGUAGE', 'OTHER__EMBEDDED', 'OTHER__IOT', 'OTHER__AR_VR', 'OTHER__ROBOTICS');
ALTER TABLE "OpWorkSkill" ALTER COLUMN "type" TYPE "OpWorkSkillType_new" USING ("type"::text::"OpWorkSkillType_new");
ALTER TYPE "OpWorkSkillType" RENAME TO "OpWorkSkillType_old";
ALTER TYPE "OpWorkSkillType_new" RENAME TO "OpWorkSkillType";
DROP TYPE "public"."OpWorkSkillType_old";
COMMIT;
